name: Array API Tests (NumPy 1.26)

on: [push, pull_request]

jobs:
  array-api-tests-numpy-latest:
    uses: ./.github/workflows/array-api-tests.yml
    with:
      package-name: numpy
      package-version: '== 1.26.*'
      xfails-file-extra: '-1-26'
      python-versions: '[''3.10'', ''3.12'']'
      pytest-extra-args: -n 4
      extra-env-vars: |
        ARRAY_API_TESTS_XFAIL_MARK=skip
