name: Docs Deploy

on:
  push:
    branches:
      - main

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    environment:
      name: docs-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: docs-build.yml
          name: docs-build
          path: docs/_build/html

      # Note, the gh-pages deployment requires setting up a SSH deploy key.
      # See
      # https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          force: no
